const child_process=require('child_process');const jwt=require('jsonwebtoken');const express=require('express');const Docker=require('dockerode');const DB=require('better-sqlite3');const fs=require('fs'),path=require('path'),os=require('os'),http=require('http'),crypto=require('crypto');const WebSocket=require('ws');
function deriveState(i){if(!i||!i.State||!i.State.Running)return'offline';let h=i.State.Health&&i.State.Health.Status;if(h==='healthy')return'running';if(h==='starting'||h==='unhealthy')return'starting';return'running';}
function cleanLine(s){s=String(s);s=s.replace(/\u001b[=>]/g,'');s=s.replace(/\u001b\[[0-9;?]*([A-Za-z])/g,function(m,c){return c==='m'?m:''});s=s.replace(/\r/g,'');s=s.replace(/^[>.]+/,'');return s.trimEnd();}
const app=express();app.use(express.json({limit:'100mb'}));app.use(express.raw({type:'text/plain',limit:'100mb'}));const docker=new Docker({socketPath:'/var/run/docker.sock'}),db=new DB(path.join(process.env.HYPIXEL_DATA_DIR||'/var/lib/hypixel/servers','panel.db')),base=process.env.HYPIXEL_DATA_DIR||'/var/lib/hypixel/servers',token=process.env.WINGS_TOKEN||'';
const auth=(q,r,n)=>{if((q.headers.authorization||'')!=='Bearer '+token)return r.status(401).json({error:'Unauthorized'});n()};const row=id=>db.prepare('SELECT * FROM servers WHERE id=?').get(id);const root=id=>path.join(base,id);const safe=(id,p='/')=>{let b=path.resolve(root(id)),f=path.resolve(b,'.'+('/'+p).replaceAll('\\','/'));if(f!==b&&!f.startsWith(b+path.sep))throw Error('Invalid path');return f};const cont=id=>docker.getContainer(row(id)?.container_id||('mcpanel-'+id));
app.get('/api/system',auth,async(q,r)=>{try{let x=await docker.info(),cpus=os.cpus(),memTotal=os.totalmem(),memFree=os.freemem(),root=fs.statfsSync('/'),diskTotal=Number(root.blocks)*Number(root.bsize),diskFree=Number(root.bavail)*Number(root.bsize),diskUsed=diskTotal-diskFree,devices='';try{devices=child_process.execFileSync('lsblk',['-dn','-o','NAME,ROTA,TYPE'],{encoding:'utf8'}).trim()}catch{}let rows=devices.split('\n').map(v=>v.trim()).filter(Boolean),ssd=rows.some(v=>/\s0\s+disk$/.test(v)),diskType=ssd?'SSD/NVMe':(rows.length?'HDD':'Unknown');try{let dfout=child_process.execFileSync('df',['-B1','--output=source,size,used','-x','tmpfs','-x','devtmpfs','-x','overlay'],{encoding:'utf8'}).trim().split('\n').slice(1);let seen={},tt=0,tu=0;for(let ln of dfout){let parts=ln.trim().split(/\s+/);if(parts.length<3)continue;let src=parts[0];if(!src.startsWith('/dev/'))continue;if(seen[src])continue;seen[src]=1;tt+=Number(parts[1]||0);tu+=Number(parts[2]||0)}if(tt>0){diskTotal=tt;diskUsed=tu;diskFree=tt-tu}}catch{}r.json({architecture:process.arch,cpu_count:cpus.length,cpu_model:cpus[0]?.model||'unknown',cpu_speed_mhz:cpus[0]?.speed||0,kernel_version:os.release(),os:os.platform(),hostname:os.hostname(),uptime:os.uptime(),version:'keztraviamc',memory:{total:memTotal,free:memFree,used:memTotal-memFree},disk:{mount:'/',total:diskTotal,free:diskFree,used:diskUsed,type:diskType,devices:rows}})}catch(e){r.status(500).json({error:e.message})}});
app.get('/api/servers',auth,async(q,r)=>{let out=[];for(let s of db.prepare('SELECT * FROM servers').all()){try{let i=await cont(s.id).inspect();out.push({uuid:s.id,uuidShort:s.id.slice(0,8),name:s.name,state:i.State.Running?'running':'offline',status:i.State.Status,container:{id:i.Id,name:i.Name.slice(1),image:i.Config.Image},limits:{memory:s.ram,cpu:s.cpu,disk:s.disk_gb}})}catch{}}r.json(out)});
app.get('/api/servers/:id',auth,async(q,r)=>{let s=row(q.params.id);if(!s)return r.sendStatus(404);try{let c=cont(s.id),i=await c.inspect(),st=await c.stats({stream:false}),cpu=0;if(st.cpu_stats&&st.precpu_stats){let dc=st.cpu_stats.cpu_usage.total_usage-st.precpu_stats.cpu_usage.total_usage,ds=st.cpu_stats.system_cpu_usage-st.precpu_stats.system_cpu_usage;if(ds>0)cpu=(dc/ds)*st.cpu_stats.online_cpus*100}r.json({uuid:s.id,uuidShort:s.id.slice(0,8),name:s.name,state:i.State.Running?'running':'offline',status:i.State.Status,is_suspended:false,utilization:{memory_bytes:st.memory_stats?.usage||0,cpu_absolute:cpu,disk_bytes:0,network:{rx_bytes:0,tx_bytes:0},uptime:i.State.StartedAt?Math.max(0,Date.now()-Date.parse(i.State.StartedAt)):0},container:{id:i.Id,name:i.Name.slice(1),image:i.Config.Image},limits:{memory:s.ram,cpu:s.cpu,disk:s.disk_gb}})}catch(e){r.status(500).json({error:e.message})}});
app.post('/api/servers/:id/power',auth,async(q,r)=>{try{let c=cont(q.params.id),a=q.body.action;if(a==='start')await c.start();else if(a==='stop')await c.stop({t:10});else if(a==='restart')await c.restart({t:10});else if(a==='kill')await c.kill();else return r.status(422).json({error:'Invalid power action'});r.sendStatus(202)}catch(e){r.status(500).json({error:e.message})}});
app.post('/api/servers/:id/commands',auth,async(q,r)=>{try{let c=cont(q.params.id);for(let command of q.body.commands||[]){let e=await c.exec({Cmd:['sh','-lc',command],AttachStdout:true,AttachStderr:true});await e.start({})}r.sendStatus(204)}catch(e){r.status(500).json({error:e.message})}});
app.get('/api/servers/:id/logs',auth,async(q,r)=>{try{let x=await cont(q.params.id).logs({stdout:true,stderr:true,tail:+q.query.size||100});r.json({data:x.toString()})}catch(e){r.status(500).json({error:e.message})}});
app.get('/api/servers/:id/files/list-directory',auth,(q,r)=>{try{let d=safe(q.params.id,q.query.directory||'/');fs.mkdirSync(d,{recursive:true});const mimeOf=(n,isDir)=>{if(isDir)return'inode/directory';let e=path.extname(n).toLowerCase();let m={'.json':'application/json','.yml':'text/yaml','.yaml':'text/yaml','.txt':'text/plain','.properties':'text/plain','.jar':'application/java-archive','.env':'text/plain','.log':'text/plain','.sh':'text/x-shellscript','.md':'text/markdown','.js':'application/javascript','.toml':'text/plain','.conf':'text/plain','.png':'image/png','.jpg':'image/jpeg','.gif':'image/gif','.zip':'application/zip','.gz':'application/gzip','.tar':'application/x-tar'};return m[e]||'application/octet-stream'};r.json(fs.readdirSync(d,{withFileTypes:true}).map(x=>{let f=path.join(d,x.name);let s;try{s=fs.statSync(f)}catch{s=fs.lstatSync(f)}let isDir=x.isDirectory(),isFile=x.isFile(),isLink=x.isSymbolicLink();let perm=(s.mode&0o777).toString(8).padStart(3,'0');let modeStr=(isDir?'d':(isLink?'l':'-'))+['---','--x','-w-','-wx','r--','r-x','rw-','rwx'][(s.mode>>6)&7]+['---','--x','-w-','-wx','r--','r-x','rw-','rwx'][(s.mode>>3)&7]+['---','--x','-w-','-wx','r--','r-x','rw-','rwx'][s.mode&7];return{name:x.name,created:s.ctime.toISOString(),modified:s.mtime.toISOString(),mode:modeStr,mode_bits:perm,size:isDir?0:s.size,directory:isDir,file:isFile,symlink:isLink,mime:mimeOf(x.name,isDir)}}))}catch(e){r.status(400).json({error:e.message})}});
app.get('/api/servers/:id/files/contents',auth,(q,r)=>{try{let f=safe(q.params.id,q.query.file),s=fs.statSync(f);r.set('Content-Length',s.size).type('text/plain').send(fs.readFileSync(f))}catch(e){r.status(404).json({error:e.message})}});
app.post('/api/servers/:id/files/write',auth,(q,r)=>{try{let f=safe(q.params.id,q.query.file);fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,Buffer.isBuffer(q.body)?q.body:Buffer.from(String(q.body)));r.sendStatus(204)}catch(e){r.status(400).json({error:e.message})}});
app.post('/api/servers/:id/files/create-directory',auth,(q,r)=>{try{fs.mkdirSync(safe(q.params.id,path.join(q.body.path||'/',q.body.name)),{recursive:true});r.sendStatus(204)}catch(e){r.status(400).json({error:e.message})}});
app.post('/api/servers/:id/files/delete',auth,(q,r)=>{try{for(let x of q.body.files||[])fs.rmSync(safe(q.params.id,path.join(q.body.root||'/',x)),{recursive:true,force:true});r.sendStatus(204)}catch(e){r.status(400).json({error:e.message})}});
function fileObj(fp){let st=fs.statSync(fp);let n=path.basename(fp);let isDir=st.isDirectory();let ext=path.extname(n).toLowerCase();let mm={'.json':'application/json','.yml':'text/yaml','.yaml':'text/yaml','.txt':'text/plain','.properties':'text/plain','.jar':'application/java-archive','.log':'text/plain','.sh':'text/x-shellscript','.md':'text/markdown','.js':'application/javascript','.zip':'application/zip','.gz':'application/gzip','.tar':'application/x-tar'};let mime=isDir?'inode/directory':(mm[ext]||'application/octet-stream');let mode=(st.mode&0o777).toString(8);return{name:n,created:st.ctime.toISOString(),modified:st.mtime.toISOString(),mode:(isDir?'d':'-')+['---','--x','-w-','-wx','r--','r-x','rw-','rwx'][(st.mode>>6)&7]+['---','--x','-w-','-wx','r--','r-x','rw-','rwx'][(st.mode>>3)&7]+['---','--x','-w-','-wx','r--','r-x','rw-','rwx'][st.mode&7],mode_bits:mode,size:st.size,directory:isDir,file:!isDir,symlink:false,mime}}
function runCmd(cmd,args,cwd){return new Promise((res,rej)=>{let p=child_process.spawn(cmd,args,{cwd});let er='';p.stderr.on('data',d=>er+=d);p.on('error',rej);p.on('close',c=>c===0?res():rej(new Error(cmd+' exit '+c+': '+er)))})}
app.post('/api/servers/:id/files/compress',auth,async(q,r)=>{try{let rt=q.body.root||'/';let base=safe(q.params.id,rt);let files=(q.body.files||[]).map(String);let stamp=new Date().toISOString().replace(/[:.]/g,'').replace('T','_').slice(0,15);let arch='archive-'+stamp+'.tar.gz';let out=safe(q.params.id,path.join(rt,arch));await runCmd('tar',['-czf',out,'-C',base,...files],base);r.json(fileObj(out))}catch(e){r.status(500).json({error:e.message})}});
app.post('/api/servers/:id/files/decompress',auth,async(q,r)=>{try{let rt=q.body.root||'/';let base=safe(q.params.id,rt);let file=String(q.body.file||'');let full=safe(q.params.id,path.join(rt,file));let low=file.toLowerCase();if(low.endsWith('.zip')){await runCmd('unzip',['-o',full,'-d',base],base)}else if(low.endsWith('.tar.gz')||low.endsWith('.tgz')){await runCmd('tar',['-xzf',full,'-C',base],base)}else if(low.endsWith('.tar')){await runCmd('tar',['-xf',full,'-C',base],base)}else if(low.endsWith('.gz')){await runCmd('gunzip',['-kf',full],base)}else{throw new Error('Unsupported archive format')}r.sendStatus(204)}catch(e){r.status(500).json({error:e.message})}});
app.post('/api/servers/:id/files/copy',auth,(q,r)=>{try{let loc=String(q.body.location||'');let src=safe(q.params.id,loc);let dir=path.dirname(src);let ext=path.extname(loc);let bn=path.basename(loc,ext);let dst=path.join(dir,bn+' copy'+ext);let i=1;while(fs.existsSync(dst)){dst=path.join(dir,bn+' copy '+(++i)+ext)}let st=fs.statSync(src);if(st.isDirectory())fs.cpSync(src,dst,{recursive:true});else fs.copyFileSync(src,dst);r.sendStatus(204)}catch(e){r.status(500).json({error:e.message})}});
app.post('/api/servers/:id/files/chmod',auth,(q,r)=>{try{let rt=q.body.root||'/';for(let x of q.body.files||[]){let m=parseInt(String(x.mode),8);if(!isNaN(m))fs.chmodSync(safe(q.params.id,path.join(rt,x.file)),m)}r.sendStatus(204)}catch(e){r.status(400).json({error:e.message})}});
app.post('/api/servers/:id/files/pull',auth,async(q,r)=>{try{let url=String(q.body.url||'');let dir=q.body.directory||'/';if(!/^https?:\/\//.test(url))throw new Error('Invalid URL');let fn=q.body.filename||path.basename(new URL(url).pathname)||'download';let dest=safe(q.params.id,path.join(dir,fn));fs.mkdirSync(path.dirname(dest),{recursive:true});r.sendStatus(202);let mod=url.startsWith('https')?require('https'):require('http');let get=(u,depth)=>{if(depth>5)return;mod.get(u,res2=>{if(res2.statusCode>=300&&res2.statusCode<400&&res2.headers.location){return get(res2.headers.location,depth+1)}let ws2=fs.createWriteStream(dest);res2.pipe(ws2)}).on('error',()=>{})};get(url,0)}catch(e){try{r.status(500).json({error:e.message})}catch(_){} }});
app.put('/api/servers/:id/files/rename',auth,(q,r)=>{try{for(let x of q.body.files||[])fs.renameSync(safe(q.params.id,path.join(q.body.root||'/',x.from)),safe(q.params.id,path.join(q.body.root||'/',x.to)));r.sendStatus(204)}catch(e){r.status(400).json({error:e.message})}});
app.post('/api/servers/:id/sync',auth,(q,r)=>r.sendStatus(204));app.post('/api/servers/:id/reinstall',auth,(q,r)=>r.sendStatus(202));app.post('/api/servers/:id/backup',auth,(q,r)=>r.sendStatus(202));app.post('/api/servers/:id/backup/:backup/restore',auth,(q,r)=>r.sendStatus(202));app.delete('/api/servers/:id/backup/:backup',auth,(q,r)=>r.sendStatus(204));app.delete('/api/servers/:id',auth,async(q,r)=>{try{await cont(q.params.id).remove({force:true});r.sendStatus(204)}catch(e){r.status(500).json({error:e.message})}});
const PANEL_URL=(process.env.PANEL_URL||'http://127.0.0.1:8083').replace(/\/$/,'');
const DAEMON_AUTH=(process.env.DAEMON_TOKEN_ID||'')+'.'+token;
function panelReq(method,pathname,body){return new Promise((resolve,reject)=>{let u=new URL(PANEL_URL+pathname),data=body?JSON.stringify(body):null,mod=u.protocol==='https:'?require('https'):http;let req=mod.request({hostname:u.hostname,port:u.port||(u.protocol==='https:'?443:80),path:u.pathname,method,headers:{'Authorization':'Bearer '+DAEMON_AUTH,'Accept':'application/json','Content-Type':'application/json',...(data?{'Content-Length':Buffer.byteLength(data)}:{})}},res=>{let b='';res.on('data',c=>b+=c);res.on('end',()=>{if(res.statusCode>=200&&res.statusCode<300){try{resolve(b?JSON.parse(b):{})}catch{resolve({})}}else reject(new Error('panel '+res.statusCode+' '+b))})});req.on('error',reject);if(data)req.write(data);req.end()})}
const EGG_TYPE={'0b671b89-5063-478e-8111-39a16e4cd0b8':'PAPER','da5e9445-63dd-4815-a163-844b3a27b0e7':'BUNGEECORD','b0d8a7f0-2284-47cd-99a7-50cd65d2b992':'FORGE','eab390ac-4021-4d94-b230-da0bb146ea44':'SPONGEVANILLA','40b6c3c8-3dfe-441b-aed1-99bea6bc0d87':'VANILLA','ae634b39-884d-4d50-be51-3da8f5dee928':'FABRIC'};
function eggType(egg){egg=egg||{};let uuidHit=EGG_TYPE[egg.id];if(uuidHit)return uuidHit;let n=String(egg.name||'').toLowerCase();if(n.includes('paper'))return'PAPER';if(n.includes('bungee')||n.includes('waterfall'))return'BUNGEECORD';if(n.includes('velocity'))return'VELOCITY';if(n.includes('forge')&&n.includes('neo'))return'NEOFORGE';if(n.includes('forge'))return'FORGE';if(n.includes('fabric'))return'FABRIC';if(n.includes('quilt'))return'QUILT';if(n.includes('sponge'))return'SPONGEVANILLA';if(n.includes('purpur'))return'PURPUR';if(n.includes('pufferfish'))return'PUFFERFISH';if(n.includes('spigot'))return'SPIGOT';if(n.includes('vanilla'))return'VANILLA';return'VANILLA';}
function itzgImage(img){let m=String(img||'').match(/java[_:]?(\d+)/i);return 'itzg/minecraft-server:java'+(m?m[1]:'21')}
async function ensureNetwork(){try{await docker.getNetwork('mcpanel_net').inspect()}catch{try{await docker.createNetwork({Name:'mcpanel_net'})}catch{}}}
app.post('/api/servers',auth,async(q,r)=>{
  const uuid=q.body.uuid;const startOnCompletion=q.body.start_on_completion!==false;
  if(!uuid)return r.status(422).json({error:'uuid required'});
  r.sendStatus(204);
  (async()=>{
    try{
      const cfg=await panelReq('GET','/api/remote/servers/'+uuid);
      const s=cfg.settings||{},env=s.environment||{},build=s.build||{},alloc=(s.allocations&&s.allocations.default)||{};
      const type=eggType(s.egg);
      const image=itzgImage((s.container&&s.container.image));
      let _ml=Number(build.memory_limit||0);const memMiB=_ml>0?_ml:6144;const _unlimited=_ml<=0;const _cpu=Number(build.cpu_limit||0);const _nano=_cpu>0?Math.round(_cpu/100*1e9):0;const port=Number(alloc.port||25565);
      const version=env.MINECRAFT_VERSION||'latest';
      const dataDir=path.join(base,uuid);fs.mkdirSync(dataDir,{recursive:true});
      await ensureNetwork();
      try{await new Promise((res,rej)=>docker.pull(image,(e,st)=>{if(e)return rej(e);docker.modem.followProgress(st,er=>er?rej(er):res())}))}catch(e){}
      const name='mcpanel-'+uuid;
      try{let old=docker.getContainer(name);await old.remove({force:true})}catch{}
      const containerEnv=['EULA=TRUE','TYPE='+type,'VERSION='+version,'MEMORY='+memMiB+'M','INIT_MEMORY=256M','SERVER_PORT='+port,'UID=0','GID=0','ONLINE_MODE=FALSE','USE_AIKAR_FLAGS=true','ENABLE_RCON=false','JVM_OPTS=-DPaper.IgnoreWorldDataVersion=true'];
      const c=await docker.createContainer({Image:image,name,Hostname:uuid.slice(0,12),Env:containerEnv,ExposedPorts:{[port+'/tcp']:{},[port+'/udp']:{}},HostConfig:{Binds:[dataDir+':/data'],PortBindings:{[port+'/tcp']:[{HostPort:String(port)}],[port+'/udp']:[{HostPort:String(port)}]},Memory:_unlimited?0:memMiB*1048576,NanoCpus:_nano,NetworkMode:'mcpanel_net',SecurityOpt:['no-new-privileges'],CapDrop:['NET_RAW','SYS_ADMIN','SYS_MODULE'],RestartPolicy:{Name:'unless-stopped'}},Tty:true,OpenStdin:true});
      const info=await c.inspect();
      const now=Math.floor(Date.now()/1000);
      db.prepare('INSERT OR REPLACE INTO servers (id,name,type,version,docker_image,java_version,ram,cpu,port,status,container_id,owner_id,node_id,allocation_id,disk_gb,created_at,updated_at) VALUES (?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?,?)').run(uuid,(s.meta&&s.meta.name)||uuid.slice(0,8),type,version,image,(image.match(/java(\d+)/)||[])[1]||'21',memMiB,Number(build.cpu_limit||0),port,'installing',info.Id,(db.prepare('SELECT id FROM users LIMIT 1').get()||{}).id||'admin','local-node','alloc-'+port,Number(build.disk_space||0)/1024|0,now,now);
      let _started=false;for(let _a=0;_a<3&&!_started;_a++){try{await c.start();_started=true}catch(e){await new Promise(r2=>setTimeout(r2,3000))}}
      db.prepare('UPDATE servers SET status=? WHERE id=?').run(_started?'running':'installing',uuid);
      await panelReq('POST','/api/remote/servers/'+uuid+'/install',{successful:true,reinstall:false});
    }catch(e){try{await panelReq('POST','/api/remote/servers/'+uuid+'/install',{successful:false,reinstall:false})}catch{}}
  })();
});
const busboy=require('busboy');
function verifyUploadToken(tok){try{return jwt.verify(String(tok||''),token)}catch{return null}}
app.post('/upload/file',(q,r)=>{
  const claims=verifyUploadToken(q.query.token);
  if(!claims)return r.status(401).json({error:'invalid token'});
  const uuid=claims.server_uuid;
  if(!uuid)return r.status(422).json({error:'no server_uuid'});
  let dir=q.query.directory||'/';
  let destDir;
  try{destDir=safe(uuid,dir)}catch{return r.status(400).json({error:'bad path'})}
  fs.mkdirSync(destDir,{recursive:true});
  let bb;
  try{bb=busboy({headers:q.headers,limits:{fileSize:8*1024*1024*1024}})}catch(e){return r.status(400).json({error:'bad form'})}
  let hadError=false,pending=0,finished=false;
  const done=()=>{if(finished&&pending===0&&!hadError)r.status(204).end()};
  bb.on('file',(name,file,info)=>{
    pending++;
    const fname=path.basename(info.filename||'upload.bin');
    let out;
    try{out=fs.createWriteStream(path.join(destDir,fname))}catch(e){hadError=true;file.resume();pending--;return}
    file.on('data',()=>{});
    file.pipe(out);
    file.on('limit',()=>{hadError=true;try{out.destroy()}catch{}});
    out.on('close',()=>{pending--;done()});
    out.on('error',()=>{hadError=true;pending--;if(!r.headersSent)r.status(500).json({error:'write failed'})});
  });
  bb.on('close',()=>{finished=true;done()});
  bb.on('error',()=>{if(!r.headersSent)r.status(500).json({error:'upload error'})});
  q.pipe(bb);
});
app.get('/download/file',(q,r)=>{
  const claims=verifyUploadToken(q.query.token);
  if(!claims)return r.status(401).json({error:'invalid token'});
  const uuid=claims.server_uuid;const fp=claims.file_path||q.query.file;
  if(!uuid||!fp)return r.status(422).json({error:'missing'});
  let full;
  try{full=safe(uuid,fp)}catch{return r.status(400).json({error:'bad path'})}
  if(!fs.existsSync(full)||fs.statSync(full).isDirectory())return r.status(404).json({error:'not found'});
  r.download(full,path.basename(full));
});
const srv=http.createServer(app),wss=new WebSocket.Server({noServer:true});async function runtimeStats(id){let c=cont(id),i=await c.inspect(),st=await c.stats({stream:false}),cpu=0;if(st.cpu_stats&&st.precpu_stats){let dc=(st.cpu_stats.cpu_usage?.total_usage||0)-(st.precpu_stats.cpu_usage?.total_usage||0),ds=(st.cpu_stats.system_cpu_usage||0)-(st.precpu_stats.system_cpu_usage||0);if(ds>0)cpu=(dc/ds)*(st.cpu_stats.online_cpus||1)*100}let rx=0,tx=0;for(let n of Object.values(st.networks||{})){rx+=Number(n.rx_bytes||0);tx+=Number(n.tx_bytes||0)}let disk=0;try{disk=Number(child_process.execFileSync('du',['-sb',root(id)],{encoding:'utf8'}).split('\t')[0])}catch{}return{state:deriveState(i),utilization:{memory_bytes:st.memory_stats?.usage||0,cpu_absolute:cpu,disk_bytes:disk,network:{rx_bytes:rx,tx_bytes:tx},uptime:i.State.StartedAt?Math.max(0,Date.now()-Date.parse(i.State.StartedAt)):0}}}
const HIST={};
async function sampleLight(id){try{let c=cont(id),i=await c.inspect();if(!i.State.Running)return{state:'offline',mem:0,cpu:0,rx:0,tx:0,uptime:0};let _ds=deriveState(i);let st=await c.stats({stream:false}),cpu=0;if(st.cpu_stats&&st.precpu_stats){let dc=(st.cpu_stats.cpu_usage?.total_usage||0)-(st.precpu_stats.cpu_usage?.total_usage||0),ds=(st.cpu_stats.system_cpu_usage||0)-(st.precpu_stats.system_cpu_usage||0);if(ds>0)cpu=(dc/ds)*(st.cpu_stats.online_cpus||1)*100}let rx=0,tx=0;for(let n of Object.values(st.networks||{})){rx+=Number(n.rx_bytes||0);tx+=Number(n.tx_bytes||0)}return{state:_ds,mem:st.memory_stats?.usage||0,cpu,rx,tx,uptime:i.State.StartedAt?Math.max(0,Date.now()-Date.parse(i.State.StartedAt)):0}}catch(e){return null}}
setInterval(async()=>{try{let rows=db.prepare('SELECT id FROM servers').all();for(let r of rows){let smp=await sampleLight(r.id);if(!smp)continue;if(!HIST[r.id])HIST[r.id]=[];HIST[r.id].push({t:Date.now(),...smp});if(HIST[r.id].length>20)HIST[r.id].shift();}}catch(e){}},1000);
function histPayload(h){return JSON.stringify({memory_bytes:h.mem,cpu_absolute:h.cpu,disk_bytes:0,network:{rx_bytes:h.rx,tx_bytes:h.tx},uptime:h.uptime,state:h.state});}
async function buildContainer(uuid){const cfg=await panelReq('GET','/api/remote/servers/'+uuid);const s=cfg.settings||{},env=s.environment||{},build=s.build||{},alloc=(s.allocations&&s.allocations.default)||{};const type=eggType(s.egg);const image=itzgImage((s.container&&s.container.image));let _ml=Number(build.memory_limit||0);const memMiB=_ml>0?_ml:6144;const _unlimited=_ml<=0;const _cpu=Number(build.cpu_limit||0);const _nano=_cpu>0?Math.round(_cpu/100*1e9):0;const port=Number(alloc.port||25565);const version=env.MINECRAFT_VERSION||'latest';const jarFile=(env.SERVER_JARFILE||'server.jar').replace(/[^A-Za-z0-9._-]/g,'');const dataDir=path.join(base,uuid);fs.mkdirSync(dataDir,{recursive:true});let _jarExists=false;try{_jarExists=fs.existsSync(path.join(dataDir,jarFile))&&fs.statSync(path.join(dataDir,jarFile)).size>1024}catch(e){}syncGeyserPort(uuid,port);await ensureNetwork();const name='mcpanel-'+uuid;try{let old=docker.getContainer(name);await old.remove({force:true})}catch{}const containerEnv=_jarExists?['EULA=TRUE','TYPE=CUSTOM','CUSTOM_SERVER=/data/'+jarFile,'SERVER_JARFILE='+jarFile,'MEMORY='+memMiB+'M','INIT_MEMORY=256M','SERVER_PORT='+port,'UID=0','GID=0','ONLINE_MODE=FALSE','USE_AIKAR_FLAGS=true','ENABLE_RCON=false','SKIP_SERVER_PROPERTIES=false','JVM_OPTS=-DPaper.IgnoreWorldDataVersion=true']:['EULA=TRUE','TYPE='+type,'VERSION='+version,'SERVER_JARFILE='+jarFile,'MEMORY='+memMiB+'M','INIT_MEMORY=256M','SERVER_PORT='+port,'UID=0','GID=0','ONLINE_MODE=FALSE','USE_AIKAR_FLAGS=true','ENABLE_RCON=false','JVM_OPTS=-DPaper.IgnoreWorldDataVersion=true'];const c=await docker.createContainer({Image:image,name,Hostname:uuid.slice(0,12),Env:containerEnv,ExposedPorts:{[port+'/tcp']:{},[port+'/udp']:{}},HostConfig:{Binds:[dataDir+':/data'],PortBindings:{[port+'/tcp']:[{HostPort:String(port)}],[port+'/udp']:[{HostPort:String(port)}]},Memory:_unlimited?0:memMiB*1048576,NanoCpus:_nano,NetworkMode:'mcpanel_net',SecurityOpt:['no-new-privileges'],CapDrop:['NET_RAW','SYS_ADMIN','SYS_MODULE'],RestartPolicy:{Name:'unless-stopped'}},Tty:true,OpenStdin:true});const info=await c.inspect();db.prepare('UPDATE servers SET container_id=?,port=?,updated_at=? WHERE id=?').run(info.Id,port,Math.floor(Date.now()/1000),uuid);return c;}
async function reconcilePort(uuid){try{let want=0;try{let cfg=await panelReq('GET','/api/remote/servers/'+uuid);let a=(cfg.settings&&cfg.settings.allocations&&cfg.settings.allocations.default)||{};want=Number(a.port||0)}catch(e){return}if(!want)return;syncGeyserPort(uuid,want);let ml=0;try{let c2=await panelReq('GET','/api/remote/servers/'+uuid);ml=Number((c2.settings&&c2.settings.build&&c2.settings.build.memory_limit)||0)}catch(e){}let wantMem=ml>0?ml*1048576:0;let cl=0;try{let c3=await panelReq('GET','/api/remote/servers/'+uuid);cl=Number((c3.settings&&c3.settings.build&&c3.settings.build.cpu_limit)||0)}catch(e){}let wantNano=cl>0?Math.round(cl/100*1e9):0;let bound=0,curMem=0,curNano=0;try{let i=await cont(uuid).inspect();let pb=(i.HostConfig&&i.HostConfig.PortBindings)||{};let k=Object.keys(pb)[0]||'';bound=Number(k.split('/')[0]||0);curMem=Number((i.HostConfig&&i.HostConfig.Memory)||0);curNano=Number((i.HostConfig&&i.HostConfig.NanoCpus)||0)}catch(e){bound=-1}if(bound!==want||curMem!==wantMem||curNano!==wantNano){await buildContainer(uuid)}}catch(e){}}
async function attachLogs(ws,id){if(ws._logStream){try{ws._logStream.destroy()}catch(e){}ws._logStream=null}try{let lc=cont(id);let fi=await lc.inspect().catch(()=>null);if(!fi||!fi.State||!fi.State.Running)return;let ls=await lc.logs({follow:true,stdout:true,stderr:true,tail:0});ws._logStream=ls;ls.on('data',ch=>{let ss=ch.toString('utf8').replace(/[\x00-\x08\x0b\x0c\x0e-\x1a\x1c-\x1f]/g,'');for(let line of ss.split(/\r?\n/)){let cl=cleanLine(line);if(cl.trim())sendEvent(ws,'console output',cl)}});ls.on('error',()=>{});}catch(e){}}
async function replayLogs(ws,id){try{let lc=cont(id);let fi=await lc.inspect().catch(()=>null);if(!fi||!fi.State||!fi.State.Running)return;let since=fi.State.StartedAt?Math.floor(new Date(fi.State.StartedAt).getTime()/1000):0;let x=await lc.logs(since?{stdout:true,stderr:true,since:since,tail:1000}:{stdout:true,stderr:true,tail:500});for(let line of x.toString().split('\n')){let cl=cleanLine(line);if(cl.trim())sendEvent(ws,'console output',cl)}}catch(e){}}
function syncGeyserPort(uuid,port){try{let cfgPath=path.join(base,uuid,'plugins','Geyser-Spigot','config.yml');if(!fs.existsSync(cfgPath))return;let y=fs.readFileSync(cfgPath,'utf8');let out=[],inBedrock=false,done=false;for(let line of y.split('\n')){let top=/^[A-Za-z]/.test(line);if(top)inBedrock=/^bedrock:/.test(line);if(inBedrock&&!done&&/^(\s+)port:\s*\d+/.test(line)){line=line.replace(/^(\s+port:\s*)\d+/,'$1'+port);done=true}out.push(line)}if(done)fs.writeFileSync(cfgPath,out.join('\n'));}catch(e){}}
const sendEvent=(ws,event,...args)=>{if(ws.readyState===1)ws.send(JSON.stringify({event,args}))};
wss.on('connection',(ws,req,id)=>{let ok=false;ws.on('close',()=>{if(ws._statsTimer)clearInterval(ws._statsTimer);if(ws._logStream){try{ws._logStream.destroy()}catch(e){}}});ws.on('error',()=>{if(ws._statsTimer)clearInterval(ws._statsTimer);if(ws._logStream){try{ws._logStream.destroy()}catch(e){}}});ws.on('message',async raw=>{try{let m=JSON.parse(raw.toString()),event=m.event,args=m.args||[];if(event==='auth'){try{let _cl=jwt.verify(String(args[0]||''),token);if(_cl&&typeof _cl==='object'&&_cl.server_uuid&&_cl.server_uuid!==id){sendEvent(ws,'jwt error','token server mismatch');return}ok=true;ws._perms=(_cl&&_cl.permissions)||[];sendEvent(ws,'auth success');await attachLogs(ws,id);let x=await runtimeStats(id);if(HIST[id]&&HIST[id].length){for(let h of HIST[id])sendEvent(ws,'stats',histPayload(h));}sendEvent(ws,'stats',JSON.stringify({memory_bytes:x.utilization.memory_bytes,cpu_absolute:x.utilization.cpu_absolute,disk_bytes:x.utilization.disk_bytes,network:x.utilization.network,uptime:x.utilization.uptime,state:x.state}));if(ws._statsTimer)clearInterval(ws._statsTimer);ws._lastState=x.state;ws._statsTimer=setInterval(async()=>{try{if(ws.readyState!==1)return;let h=(HIST[id]||[]).slice(-1)[0];if(!h)return;sendEvent(ws,'stats',histPayload(h));if(h.state!==ws._lastState){let prev=ws._lastState;ws._lastState=h.state;sendEvent(ws,'status',h.state);if((prev==='offline'||!prev)&&(h.state==='starting'||h.state==='running')){sendEvent(ws,'console output','\u001b[2J\u001b[3J\u001b[H');await attachLogs(ws,id);await replayLogs(ws,id)}else if(h.state==='offline'){if(ws._logStream){try{ws._logStream.destroy()}catch(e){}ws._logStream=null}}}}catch(e){}},1000)}catch(e){sendEvent(ws,'jwt error',e.message)}return}if(!ok)return;if(event==='send stats'){let x=await runtimeStats(id);sendEvent(ws,'stats',JSON.stringify({memory_bytes:x.utilization.memory_bytes,cpu_absolute:x.utilization.cpu_absolute,disk_bytes:x.utilization.disk_bytes,network:x.utilization.network,uptime:x.utilization.uptime}))}else if(event==='send logs'){try{let st0=await runtimeStats(id);sendEvent(ws,'status',st0.state)}catch(e){}await replayLogs(ws,id)}else if(event==='send command'){let command=String(args[0]||'').trim();if(!command)return;sendEvent(ws,'console output','\u001b[36m> '+command+'\u001b[0m');try{let c=cont(id);let st=await c.attach({stream:true,stdin:true,stdout:false,stderr:false,hijack:true});st.write(command+'\n');setTimeout(()=>{try{st.end()}catch(e){}},150);}catch(e){sendEvent(ws,'console output','\u001b[31m[panel] command failed: '+e.message+'\u001b[0m')}}else if(event==='set state'){let a=String(args[0]||'');if(a==='start'){await reconcilePort(id);await cont(id).start()}else if(a==='stop')await cont(id).stop({t:10});else if(a==='restart'){await reconcilePort(id);let rc=cont(id);try{await rc.restart({t:10})}catch(e){await rc.start()}}else if(a==='kill')await cont(id).kill()}}catch(e){sendEvent(ws,'daemon error',e.message)}})});
srv.on('upgrade',(q,s,h)=>{let m=(q.url||'').match(/^\/api\/servers\/([^/]+)\/ws/);if(!m)return s.destroy();wss.handleUpgrade(q,s,h,w=>wss.emit('connection',w,q,m[1]))});srv.listen(Number(process.env.HYPIXEL_ADAPTER_PORT||8084),'127.0.0.1',()=>console.log('Hypixel adapter ready'))